name: run the tests
on:
  push
    branches:
      - main
  pull request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Unit testing
        run: |
          cd ciphers_project
          python3 manage.py test
      - name: Build and push the image
        run: |
          docker login --username benseddikismail --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/benseddikismail/ciphers-service:latest --file Dockerfile .  
          docker push ghcr.io/benseddikismail/ciphers-service:latest 

      

